# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'DemoCollectionView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'RxSwift',    '~> 3.0'
    	pod 'RxCocoa',    '~> 3.0'
end

  # Pods for DemoCollectionView


